import { chmodSync, existsSync, copyFileSync } from 'node:fs';
import chalk from 'chalk';
import { stringify as stringifyYaml } from 'yaml';
import type { WizardStep, WizardContext } from '../types.js';
import type { AppConfig, UserConfig, ExporterEntry } from '../../config/schema.js';
import { AppConfigSchema, formatConfigError } from '../../config/schema.js';
import { atomicWrite } from '../../config/write.js';
import { sectionBox, success, error, dim } from '../ui.js';

const YAML_HEADER = `# BLE Scale Sync — config.yaml
# Generated by: npm run setup
#
# WARNING: This file may contain sensitive data (passwords, tokens).
# Use \${ENV_VAR} references for secrets (resolved from .env at load time).
#
# Validate: npm run validate
# Edit:     npm run setup (edit mode)
`;

function stripWizardFields(config: Partial<AppConfig>): Record<string, unknown> {
  return { ...config };
}

function printSummary(config: Partial<AppConfig>): void {
  // Users section
  const users = config.users ?? [];
  const userLines: string[] = [];
  for (const u of users) {
    const user = u as UserConfig;
    const range = user.weight_range
      ? chalk.dim(` [${user.weight_range.min}\u2013${user.weight_range.max} kg]`)
      : '';
    const perUser = user.exporters?.length ?? 0;
    const exporterInfo = perUser > 0 ? chalk.dim(` + ${perUser} per-user exporter(s)`) : '';
    userLines.push(
      `${chalk.bold(user.name)} ${chalk.dim(`(${user.slug})`)}${range}${exporterInfo}`,
    );
  }
  console.log('\n' + sectionBox(`Users (${users.length})`, userLines.join('\n')));

  // BLE
  const mac = config.ble?.scale_mac;
  const bleText = mac ? `${chalk.bold('scale_mac:')} ${mac}` : dim('auto-discovery');
  console.log(sectionBox('BLE', bleText));

  // Scale
  const scale = config.scale;
  if (scale) {
    console.log(
      sectionBox(
        'Scale',
        `weight_unit=${chalk.bold(scale.weight_unit)}, height_unit=${chalk.bold(scale.height_unit)}`,
      ),
    );
  }

  // Global exporters
  const globalExporters = config.global_exporters ?? [];
  const exporterLines =
    globalExporters.length === 0
      ? dim('(none)')
      : globalExporters.map((e) => `- ${(e as ExporterEntry).type}`).join('\n');
  console.log(sectionBox(`Global Exporters (${globalExporters.length})`, exporterLines));

  // Runtime
  const rt = config.runtime;
  if (rt) {
    const rtText = `continuous=${chalk.bold(String(rt.continuous_mode))}, cooldown=${chalk.bold(`${rt.scan_cooldown}s`)}, dry_run=${chalk.bold(String(rt.dry_run))}`;
    console.log(sectionBox('Runtime', rtText));
  }
}

export const summaryStep: WizardStep = {
  id: 'summary',
  title: 'Review & Save',
  order: 80,

  async run(ctx: WizardContext): Promise<void> {
    printSummary(ctx.config);

    // Ensure required fields have defaults
    const finalConfig = {
      version: 1 as const,
      scale: { weight_unit: 'kg' as const, height_unit: 'cm' as const },
      unknown_user: 'nearest' as const,
      ...stripWizardFields(ctx.config),
    };

    // Validate with Zod before saving
    const result = AppConfigSchema.safeParse(finalConfig);
    if (!result.success) {
      console.log(`\n  ${error('Validation errors:')}\n`);
      console.log(formatConfigError(result.error));
      const saveAnyway = await ctx.prompts.confirm('Save anyway? (config may not load correctly)', {
        default: false,
      });
      if (!saveAnyway) {
        console.log('  Not saved.');
        return;
      }
    }

    const save = await ctx.prompts.confirm(`Save to ${ctx.configPath}?`, { default: true });
    if (!save) {
      console.log('  Not saved.');
      return;
    }

    // Serialize to YAML
    const yamlContent = YAML_HEADER + '\n' + stringifyYaml(finalConfig, { lineWidth: 0 });

    // Backup existing config before overwriting
    if (existsSync(ctx.configPath)) {
      try {
        copyFileSync(ctx.configPath, ctx.configPath + '.bak');
      } catch {
        // Non-fatal — backup may fail on some filesystems
      }
    }

    // Write atomically
    atomicWrite(ctx.configPath, yamlContent);

    // Restrict permissions on Linux/macOS
    if (ctx.platform.os === 'linux' || ctx.platform.os === 'darwin') {
      try {
        chmodSync(ctx.configPath, 0o600);
      } catch {
        // Non-fatal — may fail on some filesystems
      }
    }

    console.log(`\n  ${success(`Saved to ${ctx.configPath}`)}`);

    // Next steps
    const nextSteps = [
      `${chalk.bold('npm start')}                    ${dim('# Run once')}`,
      `${chalk.bold('CONTINUOUS_MODE=true npm start')}  ${dim('# Run in continuous mode')}`,
      `${chalk.bold('npm run validate')}             ${dim('# Validate your config')}`,
      `${chalk.bold('npm run setup')}                ${dim('# Edit configuration')}`,
    ];

    console.log('\n' + sectionBox('Next Steps', nextSteps.join('\n')));
  },
};

// Exported for testing
export { stripWizardFields, printSummary, YAML_HEADER };
